name: push_lib_widget
on: [push]
jobs:
  common:
    runs-on: ubuntu-latest
    steps:
      - name: Send
        uses: zcong1993/actions-ding@master
        with:
          dingToken: 67b3d5302637555a9ef5c9ddb06b13d9d16d02fcb6fa119792154340046ea022
          body: |
            {
              "msgtype": "markdown",
              "markdown": {
                "title": "杭州", 
                "text": "杭州这个即将发布的新版本，创始人陈航（花名“无招”）称它为“红树林”。而在此之前，每当面临重大升级，产品经理们都会取一个应景的代号，这一次，为什么是“红树林”？",
              }
            }