#name: 下载 CLI 并构建
#on:
#  push:
#    branches:
#      - master
#
#jobs:
#  prepare_and_build:
#    runs-on: ubuntu-latest  # 你可以选择适当的运行环境
#    container:
#      image: registry.cn-hangzhou.aliyuncs.com/dango/image_dx:v1.0
#    steps:
#      # 在需要的步骤中设置 Node.js 版本
#      - name: 设置 Node.js 版本
#        run:
#          echo "GitHub Actions | 打印所有环境变量"
#          env
#      - name: 设置环境
#        run: export GRADLE_USER_HOME=$(pwd)/.gradle
#
#      - name: 检出代码
#        uses: actions/checkout@v2
#
#      - name: 下载 CLI
#        env:
#          ARTIFACT_LOCATION: https://nexus.xmxdev.com/
#        run: |
#          echo "GitHub Actions | 打印所有环境变量"
#          env
#          echo "${ARTIFACT_LOCATION}"
#
