name: push_lib_widget
on:
  push:
    paths:
      - 'gradle.properties'
jobs:
  common:
    uses: DangoDX/ReusableWorkflows/.github/workflows/publish_maven_central.yml@master
    with:
      module_path: common/
    secrets: inherit
  lib_widget:
    uses: DangoDX/ReusableWorkflows/.github/workflows/publish_maven_central.yml@master
    with:
      module_path: lib/widget/
    secrets: inherit
  lib_kit:
    uses: DangoDX/ReusableWorkflows/.github/workflows/publish_maven_central.yml@master
    with:
      module_path: lib/kit/
    secrets: inherit