name: 打印提交信息
run-name: 打印提交信息 by @${{ github.actor }}

on: [push]

jobs:
#  print_env:
#    uses: Dango-dx/ReusableWorkflows/.github/workflows/print_github_info.yml@master

#  print_a:
#    uses: Dango-dx/ReusableWorkflows/.github/workflows/publish_maven_central.yml@master
#    with:
#      module_path: :lib:widget
#      artifact_name: lib_test
#      version_name: 1.3.5

  job0:
    runs-on: ubuntu-latest
    environment:
      name: publish
#    container:
      # 指定您的自定义 Docker 镜像及其标签
#      image: registry.cn-shanghai.aliyuncs.com/dango/android_ci:latest
      # platform
#      options: --platform linux/amd64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: prepare
        run: |
          env
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: publish
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD }}
        run: |
          chmod +x ./gradlew
          ./gradlew :lib:widget:clean build publishAllPublicationsToMavenCentralRepository -PRELEASE_SIGNING_ENABLED=true --no-daemon --no-parallel
        continue-on-error: true
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: aar
          path: ./lib/widget/build/outputs/aar/