name: 打印提交信息
run-name: 打印提交信息 by @${{ github.actor }}

on: [ push ]

jobs:
  job0:
    runs-on: ubuntu-latest
    environment:
      name: publish
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: prepare
        run: |
          env
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: publish
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD }}
        run: |
          chmod +x ./gradlew
          ./gradlew :lib:widget:publish --info
        continue-on-error: true
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: aar
          path: ./lib/widget/build/outputs/aar/