name: 打印提交信息
run-name: 打印提交信息 by @${{ github.actor }}

on: [push]

jobs:
  print_env:
    uses: Dango-dx/ReusableWorkflows/.github/workflows/print_github_info.yml@master

  job0:
    runs-on: ubuntu-latest
#    container:
      # 指定您的自定义 Docker 镜像及其标签
#      image: registry.cn-shanghai.aliyuncs.com/dango/android_ci:latest
      # platform
#      options: --platform linux/amd64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: 发布
        run: |
          export JAVA_HOME=$JAVA_HOME_17_X64
          env
          chmod +x ./gradlew && ./gradlew assembleRelease
      - name: check
        run: |
          cd ./app/build/intermediates/apk/debug/
          ls -a
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifacts
          path: ./app/build/intermediates/apk/debug/