name: 打印提交信息
run-name: 打印提交信息 by @${{ github.actor }}

on:
  push:
    paths:
      - 'A'
jobs:
  job0:
    runs-on: ubuntu-latest
    environment:
      name: publish
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Lint
        run: |
          ./gradlew :lib:widget:lint
      - name: 检查当前版本
        id: generate_version
        run: |
          # Generate a new version code based on the previous one
          prev_version=$(grep "VERSION_NAME" lib/widget/gradle.properties | grep -o '[0-9]\+$')
          new_version=$((prev_version + 1))
          formatted_version=$(printf "%04d" "$new_version")
          echo "$formatted_version"
          echo "new_version=$formatted_version" >> $GITHUB_OUTPUT
      - name: 之前保存的版本号
        run: |
          echo "new_version = ${{ steps.generate_version.outputs.new_version }}"
      - name: 修改本地版本号
        run: |
          # Update the versionCode in the build file
          sed -i 's/\([0-9]\+\)$/${{ steps.generate_version.outputs.new_version }}/' lib/widget/gradle.properties
      - name: 打印本地版本号
        run: |
          # Update the versionCode in the build file
          grep "VERSION_FIX" lib/widget/gradle.properties | grep '[0-9]\+$'
      - name: publish
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD }}
        run: |
          ./gradlew :lib:widget:publish
        continue-on-error: true
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: aar
          path: ./lib/widget/build/outputs/aar/