name: 打印提交信息
run-name: 打印提交信息 by @${{ github.actor }}

on: [push]

jobs:
  print_env:
    uses: Dango-dx/ReusableWorkflows/.github/workflows/print_github_info.yml@master

  job0:
    runs-on: ubuntu-latest
    steps:
      - name: Job 0
        run: |
          echo "job0"

  job00:
    runs-on: ubuntu-latest
    steps:
      - name: Job 00
        run: |
          echo "job00"

  job1:
    runs-on: ubuntu-latest
    needs: [job0]
    steps:
      - name: Job 1
        run: |
          echo "job1"

  job1_2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - name: Job 1_2
        run: |
          echo "job1_2"

  job1_3:
    runs-on: ubuntu-latest
    needs: [job1_2, job2]
    steps:
      - name: Job 1_3
        run: |
          echo "job1_3"

  job2:
    runs-on: ubuntu-latest
    needs: [job0]
    steps:
      - name: Job 2
        run: |
          echo "job2"

  job3:
    runs-on: ubuntu-latest
    needs: [job0]
    steps:
      - name: Job 3
        run: |
          echo "job3"

  job4:
    runs-on: ubuntu-latest
    needs: [job1_3, job3, job2]
    steps:
      - name: Job 4
        run: |
          echo "job4"