name: Grouped Workflow

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: 执行作业1
        run: echo "Job 1 is running"

  job2:
    runs-on: windows-latest
    steps:
      - name: 执行作业2
        run: echo "Job 2 is running"

  job3:
    runs-on: macOS-latest
    steps:
      - name: 执行作业3
        run: echo "Job 3 is running"
  group1_job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 in Group 1 Job 1
        run: echo "Step 1 in Group 1 Job 1"

  group1_job2:
    runs-on: ubuntu-latest
    needs: group1_job1  # Group 1 Job 2 依赖于 Group 1 Job 1
    steps:
      - name: Step 1 in Group 1 Job 2
        run: echo "Step 1 in Group 1 Job 2"

      - name: Step 2 in Group 1 Job 2
        run: echo "Step 2 in Group 1 Job 2"

  group2_job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 in Group 2 Job 1
        run: echo "Step 1 in Group 2 Job 1"

  group2_job2:
    runs-on: ubuntu-latest
    needs: group2_job1  # Group 2 Job 2 依赖于 Group 2 Job 1
    steps:
      - name: Step 1 in Group 2 Job 2
        run: echo "Step 1 in Group 2 Job 2"
