name: Custom Docker Image Example

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run a custom command in the custom image
        run: |
          echo "Hello from the custom Docker image!"
          env
          ls -a
          echo " ---- ---- "
          pwd

      - name: Build and package
        run: |
          # Your build commands here
          mkdir dist
          echo "Hello, world!" > dist/hello.txt


      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
         name: my-artifacts
         path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: registry.cn-shanghai.aliyuncs.com/dango/android_ci:latest  # 指定您的自定义 Docker 镜像及其标签
      options: --platform linux/amd64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: my-artifacts

      - name: 打印文件
        run: |
          env
          ls -a
          pwd

      - name: Deploy
        run: |
          # Use the downloaded artifacts for deployment
          cat hello.txt