name: push_lib_widget
on: [ push ]


jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Display changed files
        run: |
          git log ${{ github.event.before }}
          git log ${{ github.event.after }}
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }}
  push_common:
    uses: DangoDX/ReusableWorkflows/.github/workflows/publish_maven_central.yml@master
    with:
      module_path: common/
    secrets: inherit
  push_lib_widget:
    uses: DangoDX/ReusableWorkflows/.github/workflows/publish_maven_central.yml@master
    with:
      module_path: lib/widget/
    secrets: inherit
  push_lib_kit:
    uses: DangoDX/ReusableWorkflows/.github/workflows/publish_maven_central.yml@master
    with:
      module_path: lib/kit/
    secrets: inherit