name: 打印提交信息

on:
  push:
    paths:
      - '**'
jobs:
  container:
    # 指定您的自定义 Docker 镜像及其标签
    image: registry.cn-shanghai.aliyuncs.com/dango/android_ci:latest
    # platform
    options: --platform linux/amd64

  print_env:
    uses: Dango-dx/ReusableWorkflows/.github/workflows/print_github_info.yml@master

  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v2