name: push_lib_widget

on:
  push:
    paths:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: registry.cn-shanghai.aliyuncs.com/dango/android_ci:latest  # 指定您的自定义 Docker 镜像及其标签
      options: --platform linux/amd64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: 打印环境变量
        run: |
          env

      - name: Display Commit SHA
        run: |
          echo "Current Commit SHA: ${{ github.sha }}"

      - name: Display Branch/Tag Name
        run: |
          echo "Current Ref: ${{ github.ref }}"

      - name: Display Commit Author
        run: |
          echo "Commit Author: ${{ github.actor }}"
          echo "Commit Author: ${{ github.actor }}"

      - name: Display Repository Name
        run: |
          echo "Repository: ${{ github.repository }}"

      # 获取git log
      - name: Get git log
        id: git_log
        run: |
          updateLog=`git log --pretty=format:"%s" -1`
          echo "updateLog=$updateLog" >> $GITHUB_ENV

      - name: Show Latest Commit
        run: |
          git config --global --add safe.directory "*"
          git log -n 1

