name: 每隔1分钟执行示例

on: push
#  schedule:
#    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      uses: DangoDX/ReusableWorkflows/.github/workflows/publish_maven_centra_v2l.yml@master
      with:
        module_paths_v2: ['common/' , 'lib/widget/' , 'lib/kit/']
      secrets: inherit