name: 每隔1分钟执行示例

on: push
#  schedule:
#    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12, 14]
    steps:
      uses: DangoDX/ReusableWorkflows/.github/workflows/publish_maven_central.yml@master
      with:
        module_path: ['common/' , 'lib/widget/' , 'lib/kit/']
      secrets: inherit