name: Test

on:
  push:

jobs:
  build:
    uses: DangoDX/ReusableWorkflows/.github/workflows/publish_maven_central_v2.yml@master
    with:
      module_paths_v2: '{"module":["12", "14"]}'
    secrets: inherit