name: 发布 AAR

on:
  push:
    paths:
      - 'gradle.properties'

jobs:
  build:
    uses: dango2887/ReusableWorkflows/.github/workflows/publish_maven_central_v2.yml@master
    with:
#      module_paths_v2: '{"module": [":tap:core"]}'
      module_paths_v2: '{"module": [":dLib:widget", ":dLib:kit", ":tap:core"]}'
    secrets: inherit