name: Test

on:
  push:

jobs:
  build:
    uses: DangoDX/ReusableWorkflows/.github/workflows/publish_maven_central.yml@master
    with:
      module_path: common/
#      module_paths_v2: ['common/' , 'lib/widget/' , 'lib/kit/']
    secrets: inherit